### ISSUE TITLE
Проблема с плагином,тоесть спавном ентити

### ISSUE THREAD

**Issue by Dospoker** [ISRAPIL/FastCorePE#10]
### Описание вопроса
Кратко опишите проблему

### OS и версия
* Версия FastCorePE:
* Версия PHP:
* OS сервера:
* Версия игры: PE/Win10

### Крашдамп и другое

* ...

Os:Ubuntu
FastCore 1.1.0
PHP: 7
PE

Вот ошибка,это можно как то исправить
17:46:29] CRITICAL> Unhandled exception executing command 'ew shop' in ew: Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\format\Chunk, instance of pocketmine\level\Level given, called in phar:///eggwars/skywars/plugins/EggWars_v1.phar/src/Enes5519/EggWars/Command/EW.php on line 142
[17:46:29] CRITICAL> TypeError: "Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\format\Chunk, instance of pocketmine\level\Level given, called in phar:///eggwars/skywars/plugins/EggWars_v1.phar/src/Enes5519/EggWars/Command/EW.php on line 142" (EXCEPTION) in "/src/pocketmine/entity/Entity" at line 588

**Comment by AlexBrin** [comment]
Читаем ошибку и видим: отправляешь Level, а нужно Chunk

**Comment by DanilZz** [comment]
Проблема в плагине, а не в ядре
Тут только по проблемам ядра

**Comment by FaigerSYS** [comment]
Проблема как раз таки в ядре, ибо оно принимает все версии API плагинов. В этом случае, указанные версии API в плагине не должны поддерживать API этого ядра, но ядро это спокойно игнорирует и пропускает плагин на загрузку. Изменения в API делаются не просто так. Если и добавлять возможность загружать все версии API, то нужно учитывать изменения всех версий, и добавлять максимальную обратную совместимость для каждого из них
