### ISSUE TITLE
Ссоры между ядрами?

### ISSUE THREAD

**Issue by ara2am** [ISRAPIL/FastCorePE#2]
Раньше во времена Имагикла и Генезиса ссоры были. А сейчас какие7) К примеру разработчик пммп коммитит в репозитории Генезиса, стеадфаста и т. д. Где же здесь ссора7

**Comment by ara2am** [comment]
И может быть сначала русскую орфографию выучить, прежде чем писать ядра (request https://github.com/ISRAPIL/FastCorePE/pull/3) ?

**Comment by Frago9876543210** [comment]
@ara2am, файл readme писался с т9 наверное😂.

**Comment by ara2am** [comment]
@Frago9876543210 я бы тоже так подумал бы, но Т9 (исправление) вряд ли может исправить "исправляем" на "испрOвляем".

**Comment by Frago9876543210** [comment]
@ara2am, ну с вероида можно по кнопкам мазать.
