### ISSUE TITLE
Конструктивная оценка | seetch

### ISSUE THREAD

**Issue by seetch** [ISRAPIL/FastCorePE#5]
Хм, 2 месяца не кодил - **вообще**. Зашел в всеми наше любимое сообщество, увидел несколько комментариев, решил глянуть. Хотелось бы подробнее услышать об данное ядре и т.д. @seetch

**Comment by seetch** [comment]
На каких серверах стоит это ядро? Версии сервера. Создайте web часть со статистикой использования и т.д.

**Comment by ISRAPIL** [comment]
@seetch 
Привет, спасибо что не бомбишь как другие "умники". 
Позже напишу тебе в ЛС или можешь написать [МНЕ](https://vk.com/israpil14)

**Comment by DanilZz** [comment]
Ядро пока что только разрабатывается. Всё возможно... В будущем)
