### ISSUE TITLE
Путаница с мультипротоколами

### ISSUE THREAD

**Issue by FaigerSYS** [ISRAPIL/FastCorePE#8]
Как по вашему пакет транспортировки игрока будет работать на 1.0.0?

**Comment by Frago9876543210** [comment]
@FaigerSYS, никак) Ибо этого пакета в клиенте нету.

**Comment by FaigerSYS** [comment]
Тогда зачем устраивать конфуз версий? Или убирайте пакет транспортировки для настоящей обратной совместимости, или версию протокола 100. Ибо не зря их придумали

**Comment by ISRAPIL** [comment]
```
    public function transfer($address, $port = 19132)
    {
        if (isset($address) and $this->getProtocol() >= 101) {
            $pk = new TransferPacket();
            $pk->address = $address;
            $pk->port = (int)$port;
            $this->dataPacket($pk);
        }else{
            return false;
        }
    }
```


@FaigerSYS

**Comment by FaigerSYS** [comment]
@ISRAPIL , оно всё равно всегда возвращает false-подобный результат....

**Comment by FaigerSYS** [comment]
К тому же такие костыли ни к чему. Если транспортировка игрока между серверами будет играть ключевую роль (перенос между мини-играми например), то это уж никак не решение проблемы

**Comment by DanilZz** [comment]
Эмм
При чем тут порт 19132

**Comment by seetch** [comment]
@DanilZz кхм, если не указан аргумент в вызове функции, то будет порт 19132 по умолчанию.
