### ISSUE TITLE
Redstone

### ISSUE THREAD

**Issue by Bruno99** [ISRAPIL/FastCorePE#9]
### Описание вопроса
Redstone схемы не работают. (Не поддерживаются)
### OS и версия
* FastCorePE: 1.1.0
* Версия PHP: 7.0.3
* OS сервера: Linux
* Версия игры: PE/Win10

**Comment by ISRAPIL** [comment]
Так она и не разрабатывалась.  @Bruno99

**Comment by DanilZz** [comment]
Добавь сам
Тыжпрограммист

**Comment by Frago9876543210** [comment]
@Bruno99, добавил редстоун схемы, тему закрываю.
